language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: f7/GNxqgMur4QI5rFqBA8q9UBg1yzMYdMXxFT5cufarMydDd95UiQpJ02fJ2ZB9f7fgBbdiKlSZjjRpPXtcCvTMWcO1mNtFzu4IW4cgzWtluyY5W3MHMEU1C3nfrUAOgZLexxV9IFd336VKJlJMZCgx0sNyqRa0MVv6GhbPVTKMwaVLjhQJG5QXwNc+/likarLnJwHPhoXB/ONODLKjIXcVMum6p35zM8QLhc+v/573fJSVP6eiclJSUhJ9lDXoBngGlCIij7SygXd/12uD7bKiSL57yfjj6f64CgcynG8hRONF1RpEtaz3j+FO9qjbs1j9rZKx7uHMYYh9C3MBDvfQ90DdtuKFXUEZ0BRszvR8xEWuffrIfuu45fRPFwIkgwMti+xGe4KobtOplnN2YSRtUjliTf+qZXguCXQ++M4MeKk17e9ft1uXFrOmxZKgYg0bH1E1WajDpdnsxXqQ8bF4VFwaYjQ6sCMz85zXSPoM0GkfRBh4qDQbkLuxUQciPUEN5yKbAGZh9BH7CosYXEQvUtXMR9SqxOBBh/RN5i4QGBvOWlYttagghx+LC31vyIUAFsFuUE4iyMp1WcDgWdvWtvkdJhX2YuhPBk1INY7KMD6JYbdmHMLGls03U2Un1EE6a54wcnfMriz9iey0Q2sPs+N6zEF7oK3OLTUCjGv4=
  app: react-trello-testing
  on:
    repo: rosaxny/react-trello-testing
