language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy: 
  provider: heroku
  api_key:
    secure: W/1/Gt1f02xKn6eazqJiWAwetHbcChhND0O57t43Exq8nx5ihlcCIhyyHr900kzQWDn30rHWA8FdkviaxRHeab64aRPWNKtcufAhxFdlgQZ99oPy0P34KOFPVq3SSDe95E1d58E0Vp/+9VQ5u3FEP3XSyOxbo/vJtWh+gkHIcXkTYYHvK4Is/EXovrUaI+yyVd8zwjeiht1pUEZTr5Ts8XKjZ/accL8Y6BDwDDVYtDfHnFsUzu591EmgCcam4I1vGf8mTce92ipR19oCkUeFPt7iNEQ22DiVUpYrxPOJw+JcmvhwhJcno56U4vfef1CwjV3swR+J7hseREpPueaarD3CAIeIpEKgT0ftb8GSpesX4pa7pfv1+22ma6KF62tStsOZktn4jza5rq3PNwJfRbGQVguFmb1zlNxmLq8lqHPjY6LecNnIJcQfvNZc69rtl1jy3OEz4iJmcTSbv+EijaQY/orx7O3taRUIDoJWonTyW6Ui8HU/6FgmRADi4ca8TqfCRINV9mbhumE8q5HaxVBvRZCx7fXgzqlWL8vJjF2DJzMtq+BNLea+FFHEzkgWRg+57VN6HhkWHtGHvuLpTRw9RmFY70CBEARnJjwNdAQsAeq2RlbTazNWteYZEItyCuBDfuVfwNddsqjXndlYkjneteOPtysff433onMzgdw=
  app: desolate-reef-20042
  on:
    repo: rosaxny/react-trello-testing
