language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: "IBIxM68n5Yahpbt+RAH/rjBZnzNxdMi6adHqKtyhZO4hkBAMntDkVr3PeNlMYf9VHJuX6W/6G2lL7Q2OF7pd2Jw2jl8Q5W7KQPmEURZ9hPlJ/kBypVH7TOk7rqe8lxccZb4ZkCjvlUBw50znFKLxO0Wsx3ZYD4Y2D7XFOoosuoHxVhiQ60rdzxh4ydOeB8cJnJ00QAa8CV/FWtaj0QI1TNSbNPHQruquH1iyQTj8f9GKwgFFGwwpEtmEhsOfGQKegFAatzEKA31iSxNY+up7ZgFwubz3MYLSvwdCcERY7WGFuUxaDGtqqPL1qdShWf6b5g0TahKGU65IsMwgz491mkFf8YQoD/u9KwhbHKYNiwyW2FGmfS1EpmpS4fxSXYjX4HG/kY5W2DJsdcWRCca0IHbKyAyh5LslXJQwwMePuP4moQY8kSOkPpLeN8gAuGMSzMEw9D29BHauZh20QIITlaSV2lSg5iL3CSN3MN+pZBhKqSpAZA4Jzgb/qSVs3mCuh03AXVMpDPq6J04cPG9baxc3pG0tv+YpTvcGPkpud8JX1c6Tu/iT17T7WwXt7koQzsF+taUrZAGjQ3UtTU2j0m4BC/QgazqZWzuCg04U4rYby+rHPtO9PTd/FBWZbbfPCCvzuJjvu2Ox5f1mjPf1UdSIO3TH37SKy4JD2+xlBjY=
  app: react-trello-testing
  on:
    repo: rosaxny/react-trello-testing
